public virtual class Human {
    /*public Object man;
    public Object woman;*/

    public Human(String name) {
        /* this.man = man;
        this.woman = woman; */
    }

    public virtual class Man {
        public Object name;

        public Man(String name) {
//            name = 'Adam';
//            this.name = name;
        }
    }

    public virtual class Woman {
        public Object name;
        public Woman(String name) {
//            name = 'Eve';
//            this.name = name;
        }
    }
}